//! Layout application: apply_layout, its phase helpers, and animation frame dispatch.

use crate::animation_worker;
use crate::state::*;
use anyhow::{anyhow, Result};
use std::sync::atomic::Ordering;
use tracing::{debug, warn};

/// Message sent back from the apply-layout worker thread.
type ApplyWorkerMsg = (
    Result<()>,
    Vec<leopardwm_platform_win32::WidthViolation>,
    Vec<leopardwm_platform_win32::HeightViolation>,
);

impl AppState {
    /// Record a short suppression window for moved/resized feedback generated by apply_layout().
    pub(crate) fn arm_moved_or_resized_suppression<I>(&mut self, window_ids: I)
    where
        I: IntoIterator<Item = u64>,
    {
        let now = std::time::Instant::now();
        self.moved_or_resized_suppression
            .retain(|_, deadline| *deadline > now);
        let deadline = now + MOVED_OR_RESIZED_SUPPRESSION_WINDOW;
        for hwnd in window_ids {
            self.moved_or_resized_suppression.insert(hwnd, deadline);
        }
    }

    /// Returns true when a moved/resized event should be ignored due to recent apply_layout().
    pub(crate) fn should_suppress_moved_or_resized(&mut self, hwnd: u64) -> bool {
        let now = std::time::Instant::now();
        self.moved_or_resized_suppression
            .retain(|_, deadline| *deadline > now);
        self.moved_or_resized_suppression
            .get(&hwnd)
            .is_some_and(|deadline| *deadline > now)
    }

    /// Join any finished timed-out apply workers so the pending list does not grow indefinitely.
    /// Returns the number of workers reaped in this pass.
    pub(crate) fn reap_finished_pending_apply_workers(&mut self) -> usize {
        if self.pending_apply_workers.is_empty() {
            return 0;
        }
        let mut still_running = Vec::with_capacity(self.pending_apply_workers.len());
        let mut reaped = 0usize;
        for handle in self.pending_apply_workers.drain(..) {
            if handle.is_finished() {
                let _ = handle.join();
                reaped += 1;
            } else {
                still_running.push(handle);
            }
        }
        self.pending_apply_workers = still_running;
        reaped
    }

    /// Mark shutdown/revert in progress and take ownership of any timed-out apply workers.
    pub(crate) fn begin_shutdown_or_revert(&mut self) -> Vec<std::thread::JoinHandle<()>> {
        self.apply_worker_cancelled.store(true, Ordering::SeqCst);
        self.apply_epoch.fetch_add(1, Ordering::SeqCst);
        std::mem::take(&mut self.pending_apply_workers)
    }

    /// Compute animated placements and send them to the animation worker.
    ///
    /// Returns `Ok(true)` if a frame was sent, `Ok(false)` if paused or no placements.
    pub(crate) fn send_animation_frame(
        &mut self,
        worker: &animation_worker::AnimationWorkerHandle,
    ) -> Result<bool> {
        if self.paused {
            return Ok(false);
        }
        // Commit deferred min-size clears before the frame reads constraints,
        // matching the invariant maintained by apply_layout. Without this, a
        // composition change occurring during an active animation would leave
        // stale per-sibling constraints in effect for the remaining frames.
        for ws_vec in self.workspaces.values_mut() {
            for ws in ws_vec.iter_mut() {
                ws.commit_pending_min_size_clears();
            }
        }
        let mut all_placements = Vec::new();
        for (monitor_id, ws_vec) in &self.workspaces {
            let idx = self.active_workspace_idx(*monitor_id);
            if let Some(workspace) = ws_vec.get(idx) {
                if let Some(monitor) = self.monitors.get(monitor_id) {
                    let placements = workspace.compute_placements_animated(monitor.work_area);
                    all_placements.extend(placements);
                }
            }
        }
        if all_placements.is_empty() && self.layout_transition.as_ref().is_none_or(|t| t.exit_rects.is_empty()) {
            return Ok(false);
        }

        // Interpolate layout transitions (structural changes like move/expel).
        if let Some(ref transition) = self.layout_transition {
            Self::apply_transition_interpolation(transition, &mut all_placements);
        }

        // Filter out the dragged window and placeholder so SetWindowPos doesn't
        // fight the OS drag or try to position the sentinel.
        if let Some(ref drag) = self.drag_state {
            if drag.is_tiled {
                all_placements.retain(|p| {
                    p.window_id != drag.hwnd
                        && p.window_id != crate::state::DRAG_PLACEHOLDER_HWND
                });
            }
        }

        self.arm_moved_or_resized_suppression(all_placements.iter().map(|p| p.window_id));
        self.applying_layout = true;

        // Partition into live placements + ghost-thumbnail updates. Ghost
        // wids are excluded from `placements` so the worker doesn't fire
        // per-frame SetWindowPos on the cloaked source HWND.
        let (live_placements, ghost_updates) = Self::partition_for_animation(
            all_placements,
            self.layout_transition.as_ref(),
            &self.ghost_handles,
        );

        let request = animation_worker::FrameRequest {
            placements: live_placements,
            ghost_updates,
            platform_config: self.platform_config.clone(),
        };
        if let Err(e) = worker.send_frame(request) {
            self.applying_layout = false;
            return Err(anyhow::anyhow!(e));
        }
        // Reposition the border immediately — both the worker's
        // SetWindowPos calls below and this border SetWindowPos commit
        // before the next DwmFlush vsync, so the border arrives on screen
        // in the same frame as the windows. Without this the FIRST
        // animation frame paints with the stale border position, since
        // the post-frame `tick + show_border` reorder in `main.rs` only
        // fires for frames 2+ (frame 1's `AnimationFrameApplied` arrives
        // AFTER frame 1 has already been presented).
        if let Some(hwnd) = self.previous_focused_hwnd {
            if self.config.appearance.active_border {
                self.show_border(hwnd);
            }
        }
        self.update_tab_strip();
        Ok(true)
    }

    /// Recalculate layout and apply placements for all monitors.
    /// Uses animated offsets if any workspace has an active animation.
    /// No-op when tiling is paused.
    pub(crate) fn apply_layout(&mut self) -> Result<()> {
        let reaped_workers = self.reap_finished_pending_apply_workers();
        if reaped_workers > 0 {
            let managed_window_ids = self.all_managed_window_ids();
            run_visibility_recovery_pass(&managed_window_ids, "late-apply-worker");
        }

        if self.paused {
            return Ok(());
        }
        // During layout transitions, the animation worker drives positioning.
        if self.layout_transition.is_some() {
            return Ok(());
        }
        if self.apply_worker_cancelled.load(Ordering::SeqCst) {
            return Err(anyhow!(
                "Layout application skipped: shutdown/revert cleanup is in progress"
            ));
        }
        if !self.pending_apply_workers.is_empty() {
            return Err(anyhow!(
                "Layout application skipped: previous timed-out apply worker is still finishing"
            ));
        }
        self.applying_layout = true;

        // Commit any deferred min-size constraint clears scheduled by
        // composition changes (add_window / insert_at / remove_window). Done
        // here rather than eagerly at the mutation site so that a timed-out /
        // paused apply path cannot leave constraints cleared indefinitely.
        for ws_vec in self.workspaces.values_mut() {
            for ws in ws_vec.iter_mut() {
                ws.commit_pending_min_size_clears();
            }
        }

        let mut all_placements = self.collect_apply_placements();

        // Interpolate layout transitions (structural changes like move/expel).
        if let Some(ref transition) = self.layout_transition {
            Self::apply_transition_interpolation(transition, &mut all_placements);
        }

        // Filter out the dragged window and placeholder so SetWindowPos doesn't
        // fight the OS drag or try to position the sentinel.
        if let Some(ref drag) = self.drag_state {
            if drag.is_tiled {
                all_placements.retain(|p| {
                    p.window_id != drag.hwnd
                        && p.window_id != crate::state::DRAG_PLACEHOLDER_HWND
                });
            }
        }

        // Fast path: if every placement matches the last applied rect (and
        // the visible-set is unchanged), there is nothing to do. Spawning
        // the worker thread, the BeginDeferWindowPos batch, the DwmFlush,
        // size-violation queries, and the sticky-compositor nudge each take
        // tens of milliseconds; under rapid focus presses within the
        // already-visible range no scroll animation starts (so the caller
        // does not get to bypass us via `is_animating()`) and these calls
        // serialize on the daemon mutex, leaving focus events draining for
        // seconds after the user stops pressing. Returning early lets the
        // event loop catch up at near-memory speed.
        let placements_unchanged = self.placements_match_last_applied(&all_placements);
        // Tests that inject worker behavior need the worker to actually
        // run, so they opt out of the fast path.
        #[cfg(test)]
        let bypass_fast_path = self.injected_apply_placements_behavior.is_some();
        #[cfg(not(test))]
        let bypass_fast_path = false;
        if placements_unchanged && !bypass_fast_path {
            self.applying_layout = false;
            return Ok(());
        }

        self.arm_moved_or_resized_suppression(all_placements.iter().map(|p| p.window_id));

        self.record_last_placed_rects(&all_placements);

        let timeout = self.layout_apply_timeout;
        let (rx, worker_handle) = self.spawn_apply_worker(all_placements)?;

        let result = match rx.recv_timeout(timeout) {
            Ok((result, width_violations, height_violations)) => {
                let _ = worker_handle.join();
                if result.is_err() {
                    self.moved_or_resized_suppression.clear();
                }
                let constraints_changed = if result.is_ok() {
                    self.propagate_size_violations(&width_violations, &height_violations)
                } else {
                    false
                };
                // If any constraint was added, run a single guarded re-apply
                // so the corrected layout lands on the current frame instead
                // of waiting for the next user-triggered event. The inner
                // apply_layout manages its own applying_layout state; we just
                // need to release our own first so the guard at the top of
                // the recursive call can re-enter cleanly. If the inner call
                // fails (e.g. its worker times out and pauses the daemon), we
                // surface that error in place of the outer Ok — the outer
                // placements may have already landed, but the daemon state
                // needs to reflect that the corrective pass didn't complete.
                if constraints_changed && !self.reapplying_after_violation {
                    self.reapplying_after_violation = true;
                    self.applying_layout = false;
                    let reapply = self.apply_layout();
                    self.reapplying_after_violation = false;
                    if let Err(e) = reapply {
                        warn!("Re-apply after size-violation propagation failed: {}", e);
                        Err(e)
                    } else {
                        result
                    }
                } else {
                    result
                }
            }
            Err(std::sync::mpsc::RecvTimeoutError::Timeout) => {
                self.paused = true;
                // Invalidate this apply epoch so late-starting workers bail before placement calls.
                self.apply_epoch.fetch_add(1, Ordering::SeqCst);
                self.pending_apply_workers.push(worker_handle);
                self.moved_or_resized_suppression.clear();
                let msg = layout_apply_timeout_message(timeout);
                warn!("{}", msg);
                let managed_window_ids = self.all_managed_window_ids();
                run_visibility_recovery_pass(&managed_window_ids, "apply-timeout");
                Err(anyhow!(msg))
            }
            Err(std::sync::mpsc::RecvTimeoutError::Disconnected) => {
                let _ = worker_handle.join();
                self.moved_or_resized_suppression.clear();
                Err(anyhow!(
                    "Layout worker thread exited without returning a result"
                ))
            }
        };
        self.applying_layout = false;

        // Reposition border to track the focused window after layout changes
        if result.is_ok() {
            self.finalize_layout_success();
        }

        result
    }

    /// Collect animated placements for every monitor's active workspace, with debug logging.
    fn collect_apply_placements(&self) -> Vec<leopardwm_core_layout::WindowPlacement> {
        let mut all_placements = Vec::new();

        for (monitor_id, ws_vec) in &self.workspaces {
            let idx = self.active_workspace_idx(*monitor_id);
            if let Some(workspace) = ws_vec.get(idx) {
                if let Some(monitor) = self.monitors.get(monitor_id) {
                    // Use animated placements to support smooth scrolling
                    let placements = workspace.compute_placements_animated(monitor.work_area);
                    debug!(
                        "Monitor {}: {} placements for viewport {}x{} (animating: {}, scroll: {:.1}, minimized: {})",
                        monitor_id,
                        placements.len(),
                        monitor.work_area.width,
                        monitor.work_area.height,
                        workspace.is_animating(),
                        workspace.effective_scroll_offset(),
                        workspace.minimized_count()
                    );
                    for p in &placements {
                        if p.visibility == leopardwm_core_layout::Visibility::Visible {
                            debug!(
                                "  placement hwnd={:#x} col={} rect=({},{} {}x{}) vis={:?}",
                                p.window_id, p.column_index,
                                p.rect.x, p.rect.y, p.rect.width, p.rect.height,
                                p.visibility,
                            );
                        }
                    }
                    all_placements.extend(placements);
                }
            }
        }

        all_placements
    }

    /// Fast-path check: every placement matches the last applied rect and the visible-set is unchanged.
    fn placements_match_last_applied(
        &self,
        all_placements: &[leopardwm_core_layout::WindowPlacement],
    ) -> bool {
        all_placements.iter().all(|p| {
            let expected = self.last_placed_layout_rects.get(&p.window_id);
            match p.visibility {
                leopardwm_core_layout::Visibility::Visible => expected == Some(&p.rect),
                _ => expected.is_none(),
            }
        }) && {
            let current_ids: std::collections::HashSet<u64> =
                all_placements.iter().map(|p| p.window_id).collect();
            !self
                .last_placed_layout_rects
                .keys()
                .any(|id| !current_ids.contains(id))
        }
    }

    /// Record layout rects for visible placements and drain stale entries.
    fn record_last_placed_rects(
        &mut self,
        all_placements: &[leopardwm_core_layout::WindowPlacement],
    ) {
        // Record the layout rect the engine chose for each window so the
        // MovedOrResized handler can short-circuit false-positive snap-backs
        // when Windows fires EVENT_OBJECT_LOCATIONCHANGE without an actual
        // position change. Visibility::Visible placements only — off-screen
        // parked windows aren't at their "layout" rect by design.
        //
        // Drain stale entries for windows that are no longer in the active
        // layout (workspace-switch leaves their hwnds alive but they stop
        // appearing in `all_placements`, which `apply_layout` builds from
        // active workspaces only). Without this drain the fast-path's
        // "no extra entries" guard fails forever after the first
        // Ctrl+Alt+1-9 — silently nullifying the rapid-Ctrl+Alt+Right/Left
        // perf fix for every multi-workspace user.
        let active_ids: std::collections::HashSet<u64> =
            all_placements.iter().map(|p| p.window_id).collect();
        self.last_placed_layout_rects
            .retain(|id, _| active_ids.contains(id));
        for p in all_placements {
            if matches!(p.visibility, leopardwm_core_layout::Visibility::Visible) {
                self.last_placed_layout_rects.insert(p.window_id, p.rect);
            } else {
                self.last_placed_layout_rects.remove(&p.window_id);
            }
        }
    }

    /// Spawn the apply-layout worker thread; returns its result channel and join handle.
    fn spawn_apply_worker(
        &mut self,
        all_placements: Vec<leopardwm_core_layout::WindowPlacement>,
    ) -> Result<(std::sync::mpsc::Receiver<ApplyWorkerMsg>, std::thread::JoinHandle<()>)> {
        let platform_config = self.platform_config.clone();
        let apply_worker_cancelled = self.apply_worker_cancelled.clone();
        let apply_epoch_ref = self.apply_epoch.clone();
        let apply_epoch = apply_epoch_ref.fetch_add(1, Ordering::SeqCst) + 1;
        let apply_window_ids: Vec<u64> = all_placements.iter().map(|p| p.window_id).collect();
        // Drain the post-animation nudge flag so only the landing pass after
        // an actual scroll / transition fires the (w-1 → w) sticky-compositor
        // nudge. Routine applies skip it, which kills the visible Zen / Slack
        // / Cascadia 1 px wobble that used to fire on every focus shift,
        // drag, or window event.
        let post_animation_nudge = std::mem::take(&mut self.post_animation_nudge_pending);
        #[cfg(test)]
        let injected_behavior = self.injected_apply_placements_behavior;
        #[cfg(test)]
        let late_worker_recovery_count = self.late_worker_recovery_count.clone();

        let (tx, rx) = std::sync::mpsc::channel::<ApplyWorkerMsg>();
        let spawn_result = std::thread::Builder::new()
            .name("leopardwm-apply-layout".to_string())
            .spawn(move || {
                let should_cancel = || {
                    apply_worker_cancelled.load(Ordering::SeqCst)
                        || apply_epoch_ref.load(Ordering::SeqCst) != apply_epoch
                };
                if should_cancel() {
                    let _ = tx.send((Ok(()), Vec::new(), Vec::new()));
                    return;
                }

                #[cfg(test)]
                if let Some(behavior) = injected_behavior {
                    let result = match behavior {
                        TestApplyPlacementsBehavior::SleepAndSucceed(delay) => {
                            std::thread::sleep(delay);
                            Ok(())
                        }
                        TestApplyPlacementsBehavior::SleepAndFail(delay) => {
                            std::thread::sleep(delay);
                            Err(anyhow!("injected apply_placements failure"))
                        }
                    };
                    if should_cancel() {
                        run_visibility_recovery_pass(
                            &apply_window_ids,
                            "apply-cancelled-late-worker",
                        );
                        #[cfg(test)]
                        late_worker_recovery_count.fetch_add(1, Ordering::SeqCst);
                        let _ = tx.send((Ok(()), Vec::new(), Vec::new()));
                        return;
                    }
                    let _ = tx.send((result, Vec::new(), Vec::new()));
                    return;
                }

                if should_cancel() {
                    let _ = tx.send((Ok(()), Vec::new(), Vec::new()));
                    return;
                }
                let (result, width_violations, height_violations) =
                    match leopardwm_platform_win32::apply_placements(
                        &all_placements,
                        &platform_config,
                        None,
                        post_animation_nudge,
                    ) {
                        Ok(r) => (Ok(()), r.width_violations, r.height_violations),
                        Err(e) => (Err(anyhow!(e.to_string())), Vec::new(), Vec::new()),
                    };
                if should_cancel() {
                    run_visibility_recovery_pass(&apply_window_ids, "apply-cancelled-late-worker");
                    #[cfg(test)]
                    late_worker_recovery_count.fetch_add(1, Ordering::SeqCst);
                    let _ = tx.send((Ok(()), Vec::new(), Vec::new()));
                    return;
                }
                let _ = tx.send((result, width_violations, height_violations));
            });

        match spawn_result {
            Ok(handle) => Ok((rx, handle)),
            Err(e) => {
                self.applying_layout = false;
                Err(anyhow!("Failed to spawn layout worker thread: {}", e))
            }
        }
    }

    /// Feed worker-reported size violations back to the layout engine; returns whether constraints changed.
    fn propagate_size_violations(
        &mut self,
        width_violations: &[leopardwm_platform_win32::WidthViolation],
        height_violations: &[leopardwm_platform_win32::HeightViolation],
    ) -> bool {
        // Feed width/height violations back to the layout engine.
        // Skip violations where min_width/min_height >= viewport size —
        // the window is temporarily fullscreen/maximized by the app
        // itself, not genuinely enforcing a minimum that large.
        let mut constraints_changed = false;
        if !width_violations.is_empty() {
            for v in width_violations {
                let vw = self.find_window_workspace(v.window_id)
                    .map(|(mid, _)| self.viewport_width_for(mid))
                    .unwrap_or(i32::MAX);
                if v.min_width >= vw {
                    debug!(
                        "Ignoring viewport-sized width violation for window {} ({}px >= {}px viewport)",
                        v.window_id, v.min_width, vw
                    );
                    continue;
                }
                for ws_vec in self.workspaces.values_mut() {
                    for ws in ws_vec.iter_mut() {
                        if ws.contains_window(v.window_id) {
                            ws.set_window_min_width(v.window_id, v.min_width);
                            constraints_changed = true;
                        }
                    }
                }
            }
            for ws_vec in self.workspaces.values_mut() {
                for ws in ws_vec.iter_mut() {
                    if ws.apply_min_width_constraints() {
                        constraints_changed = true;
                    }
                }
            }
        }
        if !height_violations.is_empty() {
            for v in height_violations {
                let vh = self.find_window_workspace(v.window_id)
                    .and_then(|(mid, _)| self.monitors.get(&mid).map(|m| m.work_area.height))
                    .unwrap_or(i32::MAX);
                if v.min_height >= vh {
                    debug!(
                        "Ignoring viewport-sized height violation for window {} ({}px >= {}px viewport)",
                        v.window_id, v.min_height, vh
                    );
                    continue;
                }
                for ws_vec in self.workspaces.values_mut() {
                    for ws in ws_vec.iter_mut() {
                        if ws.contains_window(v.window_id) {
                            ws.set_window_min_height(v.window_id, v.min_height);
                            constraints_changed = true;
                        }
                    }
                }
            }
        }
        constraints_changed
    }

    /// Post-success bookkeeping: border, tab strip, and deduped LayoutChanged broadcast.
    fn finalize_layout_success(&mut self) {
        if let Some(hwnd) = self.previous_focused_hwnd {
            if self.config.appearance.active_border {
                self.show_border(hwnd);
            }
        }
        // Reposition tab strip overlay (mirror border lifecycle).
        self.update_tab_strip();

        // LayoutChanged broadcast with signature dedup. Animation
        // frames between two settled layouts produce identical
        // signatures so the dedup check suppresses them; only
        // structural changes (column added/removed/reordered, width
        // changed, focus moved between columns) emit.
        let sig = self.focused_layout_signature();
        if self.last_emitted_layout_sig != Some(sig) {
            self.last_emitted_layout_sig = Some(sig);
            let monitor = self.focused_monitor;
            let workspace_index = self.active_workspace_idx(monitor);
            let focused_column = self
                .workspaces
                .get(&monitor)
                .and_then(|list| list.get(workspace_index))
                .map(|ws| ws.focused_column_index());
            self.broadcast_event(leopardwm_ipc::IpcEvent::LayoutChanged {
                monitor: monitor as i64,
                workspace_index: workspace_index as u8,
                focused_column,
                columns: self.focused_layout_columns(),
            });
        }
    }
}
